### ISSUE TITLE
$metadata array

### ISSUE THREAD

**Issue by Horllameeday** [kingflamez/laravelrave-implementation#3]
Please how can I use the reference the metadata information in my controller?

**Comment by bajoski34** [comment]
Sorry, i don't understand your question, please can u rephrase it

**Comment by Horllameeday** [comment]
@bajoski34
According to the documentation, there's provision to pass in Metadata to the controller. Using the <input> tag of type 'hidden' and name=Metadata.
But when I dd($data), I didn't get how to reference the Metadata variable.

BLADE
@php
$array = array(array('metaname' => 'color', 'metavalue' => 'blue'),
                array('metaname' => 'size', 'metavalue' => 'big'));
@endphp
<h3>Buy Movie Tickets N500.00</h3>
<form method="POST" action="{{ route('pay') }}" id="paymentForm">
    {{ csrf_field() }}
    
    <input type="hidden" name="metadata" value="{{ json_encode($array) }}" > 
    <input type="submit" value="Buy"  />
</form>

CONTROLLER 
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;

//use the Rave Facade
use Rave;

class RaveController extends Controller
{

  /**
   * Initialize Rave payment process
   * @return void
   */
  public function initialize()
  {
    //This initializes payment and redirects to the payment gateway
    //The initialize method takes the parameter of the redirect URL
    Rave::initialize(route('callback'));
  }

  /**
   * Obtain Rave callback information
   * @return void
   */
  public function callback()
  {

    $data = Rave::verifyTransaction(request()->txref);
$color = $data->data->metadata->color;
if ($color == 'blue') {
        return redirect('/success');
   } 
  }
}
